### ISSUE TITLE
Epic: Helm as first-class deploy tool

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-charts#138]
We've primarily focused on using `subctl` to deploy the Operator so far. With few Helm jobs running in other repos, we frequently break Helm deployments and don't know about it quickly.

My understanding is that we want to support Helm at last as much as subctl. We've also seen a substantial number of K8s users start trying Submariner using Helm.

The end goal here is to use Helm+Operator as the default deployment tool and for Helm to be part of the automated release process.

Bugs:

- [x] Lighthouse Helm jobs broken (https://github.com/submariner-io/lighthouse/issues/504)
  - [x] https://github.com/submariner-io/lighthouse/pull/519
- [x] K8s version breaks when none passed through GHA
  - [x] https://github.com/submariner-io/shipyard/pull/580
- [x] Use CNCF-wording for maintainers 52d894c390b922c1a8612e3ed4f1957ba10a0603
- [x] Add required apiVersion field to Chart.yaml 52d894c390b922c1a8612e3ed4f1957ba10a0603
- [x] Name RBAC fields to match K8s requirements 5364eac4eb3b3a6b2a7b7a642ef58ed43d3ddffe
- [ ] Track down and fix [flaky failures](https://github.com/submariner-io/submariner-charts/actions/workflows/flake_finder.yml).
- [ ] https://github.com/norwoodj/helm-docs/pull/102

Features:

- [ ] Refactor RBAC to give submariner-operator permission to manage fine-details of RBAC and remove RBAC handling from Helm.
  - [ ] https://github.com/submariner-io/submariner-operator/issues/1105
- [x] https://github.com/submariner-io/submariner-charts/issues/134
- [ ] Subctl over Helm over Operator?
- [ ] Use a `charts/` directory https://github.com/submariner-io/submariner-charts/pull/88

Testing:

- [x] https://github.com/submariner-io/submariner-charts/issues/137
- [ ] Add "canary" Helm over Operator jobs to select repos.
  - [ ] https://github.com/submariner-io/submariner-operator/pull/1409 / https://github.com/dfarrell07/submariner-operator/pull/3
- [x] https://github.com/submariner-io/submariner-charts/pull/149
- [x] https://github.com/submariner-io/submariner-charts/issues/68
  - [x] https://github.com/submariner-io/submariner-charts/pull/147
- [x] https://github.com/submariner-io/submariner-charts/pull/149
- [x] https://github.com/submariner-io/submariner-charts/pull/148
- [x] https://github.com/submariner-io/submariner-charts/pull/153

Release:

- [x] https://github.com/submariner-io/releases/issues/87

Docs:

- [x] https://github.com/submariner-io/submariner-charts/issues/69
  - [x] https://github.com/submariner-io/submariner-charts/pull/150
  - [x] https://github.com/submariner-io/submariner-charts/pull/155
- [ ] Add inline docs for params so READMEs generated by helm-docs can consume them into tables.
- [ ] https://github.com/submariner-io/submariner-website/issues/504.
- [x] https://github.com/submariner-io/submariner-charts/pull/142
- [x] https://github.com/submariner-io/submariner/pull/1381
- [x] https://github.com/submariner-io/submariner-website/pull/530
- [x] https://github.com/submariner-io/submariner/pull/1396

**Comment by dfarrell07** [comment]
Discussions on the Automation Sync today included starting from scratch with the Helm carts. That might be the quickest path to a quality result (so much needs to be changed with the current charts) and would allow us a good Helm learning opportunity along the way.

**Comment by dfarrell07** [comment]
We should make sure the release process with the GH page works for versioned releases, branches.

**Comment by maayanf24** [comment]
This has been discussed on the issue scrub meeting and decided to close for now.
If this will become a priority it can be reopened.
Individual items are tracked
